ИТМО Асадуллин Илья HW 8
reallybigsky/formal-lang-course pull request #7
Opened 2023-04-15 03:49 UTC by reallybigsky

2023-04-16 07:51 UTC, rustam-azimov requested changes

2023-04-16 07:51 UTC, rustam-azimov commented on project/context_free_grammar.py
> +    graph: MultiDiGraph, cfg: CFG
Предусмотрите и другие форматы графа и грамматики. Файл, текст

2023-04-16 12:06 UTC, reallybigsky commented on project/context_free_grammar.py
> +    graph: MultiDiGraph, cfg: CFG
Добавил однострочные функции. Думаю, что добавлять перегрузки алгоритма по всем возможным комбинациям аргументов избыточно.

2023-04-18 09:34 UTC, rustam-azimov approved these changes

2023-04-20 12:59 UTC, merged